### ISSUE TITLE
Add user score to the metacritic plugin

### ISSUE THREAD

**Issue by emerencia** [andyeff/skybot#1]
Right now the metacritic plugin only shows one score, the critics' score. However, one of the best features of the metacritic site it that it allows to contrast and compare the critics' scores with that of "regular" users. If the averaged score of 10,000 users differs significantly than that of 50 critics, then that may additionally inform someone's opinion of a certain game. For example, maybe the game was good when it was released, but then bugs were never fixed or the project was abandoned.

I don't know if the API supports it, or if it's webscraping that the plugin is doing, but if it's not too much work I would be happy to see the user's score included as a result in the metacritic replies.

**Comment by andyeff** [comment]
Alright I'll take a better look at this, I had a quick look but didn't get the expected result, I just need to understand the way the DOM parsing works a bit more.

**Comment by andyeff** [comment]
Unfortunately the plugin gets game information from the results page, and not the individual product page.

Looking at what information is available on the results page for a game, I can see there's a hidden / dynamic <div> element that gets created when mouseover'ing a result, which contains a user score.

Sadly I don't believe I can replicate the mouseover functionality in LXML parsing to make the <div> containing the user score available, so closing this for now.
